# Generated by Django 4.2 on 2023-04-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_mymodel_delete_new1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
