# Generated by Django 4.2 on 2023-04-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_addbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
