# Generated by Django 4.2 on 2023-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaleMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('waist', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AddBook',
        ),
    ]
