# Generated by Django 4.2 on 2023-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_malemeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malemeasurement',
            name='age',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='malemeasurement',
            name='height',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='malemeasurement',
            name='waist',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='malemeasurement',
            name='weight',
            field=models.IntegerField(max_length=200),
        ),
    ]
