# Generated by Django 4.2 on 2023-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_malemeasurement_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malemeasurement',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
