# Generated by Django 4.2 on 2023-04-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_malemeasurement_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddBook',
        ),
    ]
